spring:
  kafka:
    bootstrap-servers: localhost:9092
    user-interaction-group-id: analyzer-user-interaction
    event-similarity-group-id: analyzer-event-similarity
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/analyze
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/